### PR TITLE
Add support for Camden and Newark

### PR DESCRIPTION
**Pull request by gurchik**
This change affects the database schema, which means once all current snipes in the production database are moved to the new schema, the rows' values for `campus` will likely be `null`, and will need to be changed to `NB`

### CODE REVIEW

**Comment by solojungle** [comment]
If anyone was having troubles getting it to run like I was
Remove def test(): from Line 112 & Remove test(), Line 141

**Comment by derekmaciel** [comment]
Just tested this on my local machine (commenting out mail.send since I don't have a SendGrid account) and it looks like it's working fine:

> 2016-11-09 21:14:06,972 WARNING: Notified user: (derekamaciel@gmail.com) about snipe (NK:640:135:1) [in cron.py:100]

This should be ready to be accepted and closed, although it won't be able to be pushed to the production server due to the database changes necessary as detailed above. If interested I could write a script to do that for this semester, or the production server could simply not be updated until the end of this semester, either one.

**Comment by derekmaciel** [comment]
@kaitcov

**Comment by duanalluviacity** [comment]
It works fine

**Pull request closed without merging**
